#!/usr/bin/python3
def raise_exception():
    b = 'a'
    print(1 / b)
